//
//Copyright The containerd Authors.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: services/pod/v1/pod.proto

package pod

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPodResourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPodResourcesRequest) Reset() {
	*x = GetPodResourcesRequest{}
	mi := &file_services_pod_v1_pod_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPodResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPodResourcesRequest) ProtoMessage() {}

func (x *GetPodResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_pod_v1_pod_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPodResourcesRequest.ProtoReflect.Descriptor instead.
func (*GetPodResourcesRequest) Descriptor() ([]byte, []int) {
	return file_services_pod_v1_pod_proto_rawDescGZIP(), []int{0}
}

func (x *GetPodResourcesRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type GetPodResourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PodNetnsPath  string                 `protobuf:"bytes,1,opt,name=pod_netns_path,json=podNetnsPath,proto3" json:"pod_netns_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPodResourcesResponse) Reset() {
	*x = GetPodResourcesResponse{}
	mi := &file_services_pod_v1_pod_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPodResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPodResourcesResponse) ProtoMessage() {}

func (x *GetPodResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_pod_v1_pod_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPodResourcesResponse.ProtoReflect.Descriptor instead.
func (*GetPodResourcesResponse) Descriptor() ([]byte, []int) {
	return file_services_pod_v1_pod_proto_rawDescGZIP(), []int{1}
}

func (x *GetPodResourcesResponse) GetPodNetnsPath() string {
	if x != nil {
		return x.PodNetnsPath
	}
	return ""
}

type GetPodIPsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPodIPsRequest) Reset() {
	*x = GetPodIPsRequest{}
	mi := &file_services_pod_v1_pod_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPodIPsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPodIPsRequest) ProtoMessage() {}

func (x *GetPodIPsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_pod_v1_pod_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPodIPsRequest.ProtoReflect.Descriptor instead.
func (*GetPodIPsRequest) Descriptor() ([]byte, []int) {
	return file_services_pod_v1_pod_proto_rawDescGZIP(), []int{2}
}

func (x *GetPodIPsRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type PodInterfaceIPs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ips           []string               `protobuf:"bytes,1,rep,name=ips,proto3" json:"ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodInterfaceIPs) Reset() {
	*x = PodInterfaceIPs{}
	mi := &file_services_pod_v1_pod_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodInterfaceIPs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodInterfaceIPs) ProtoMessage() {}

func (x *PodInterfaceIPs) ProtoReflect() protoreflect.Message {
	mi := &file_services_pod_v1_pod_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodInterfaceIPs.ProtoReflect.Descriptor instead.
func (*PodInterfaceIPs) Descriptor() ([]byte, []int) {
	return file_services_pod_v1_pod_proto_rawDescGZIP(), []int{3}
}

func (x *PodInterfaceIPs) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

type PodRoute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Destination   string                 `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	Gateway       string                 `protobuf:"bytes,2,opt,name=gateway,proto3" json:"gateway,omitempty"`
	InterfaceName string                 `protobuf:"bytes,3,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodRoute) Reset() {
	*x = PodRoute{}
	mi := &file_services_pod_v1_pod_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodRoute) ProtoMessage() {}

func (x *PodRoute) ProtoReflect() protoreflect.Message {
	mi := &file_services_pod_v1_pod_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodRoute.ProtoReflect.Descriptor instead.
func (*PodRoute) Descriptor() ([]byte, []int) {
	return file_services_pod_v1_pod_proto_rawDescGZIP(), []int{4}
}

func (x *PodRoute) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *PodRoute) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *PodRoute) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

type GetPodIPsResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	InterfaceIps  map[string]*PodInterfaceIPs `protobuf:"bytes,1,rep,name=interface_ips,json=interfaceIps,proto3" json:"interface_ips,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Routes        []*PodRoute                 `protobuf:"bytes,2,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPodIPsResponse) Reset() {
	*x = GetPodIPsResponse{}
	mi := &file_services_pod_v1_pod_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPodIPsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPodIPsResponse) ProtoMessage() {}

func (x *GetPodIPsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_pod_v1_pod_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPodIPsResponse.ProtoReflect.Descriptor instead.
func (*GetPodIPsResponse) Descriptor() ([]byte, []int) {
	return file_services_pod_v1_pod_proto_rawDescGZIP(), []int{5}
}

func (x *GetPodIPsResponse) GetInterfaceIps() map[string]*PodInterfaceIPs {
	if x != nil {
		return x.InterfaceIps
	}
	return nil
}

func (x *GetPodIPsResponse) GetRoutes() []*PodRoute {
	if x != nil {
		return x.Routes
	}
	return nil
}

var File_services_pod_v1_pod_proto protoreflect.FileDescriptor

const file_services_pod_v1_pod_proto_rawDesc = "" +
	"\n" +
	"\x19services/pod/v1/pod.proto\x12\x1acontainerd.services.pod.v1\"7\n" +
	"\x16GetPodResourcesRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"?\n" +
	"\x17GetPodResourcesResponse\x12$\n" +
	"\x0epod_netns_path\x18\x01 \x01(\tR\fpodNetnsPath\"1\n" +
	"\x10GetPodIPsRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"#\n" +
	"\x0fPodInterfaceIPs\x12\x10\n" +
	"\x03ips\x18\x01 \x03(\tR\x03ips\"m\n" +
	"\bPodRoute\x12 \n" +
	"\vdestination\x18\x01 \x01(\tR\vdestination\x12\x18\n" +
	"\agateway\x18\x02 \x01(\tR\agateway\x12%\n" +
	"\x0einterface_name\x18\x03 \x01(\tR\rinterfaceName\"\xa5\x02\n" +
	"\x11GetPodIPsResponse\x12d\n" +
	"\rinterface_ips\x18\x01 \x03(\v2?.containerd.services.pod.v1.GetPodIPsResponse.InterfaceIpsEntryR\finterfaceIps\x12<\n" +
	"\x06routes\x18\x02 \x03(\v2$.containerd.services.pod.v1.PodRouteR\x06routes\x1al\n" +
	"\x11InterfaceIpsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12A\n" +
	"\x05value\x18\x02 \x01(\v2+.containerd.services.pod.v1.PodInterfaceIPsR\x05value:\x028\x012\xeb\x01\n" +
	"\x03Pod\x12z\n" +
	"\x0fGetPodResources\x122.containerd.services.pod.v1.GetPodResourcesRequest\x1a3.containerd.services.pod.v1.GetPodResourcesResponse\x12h\n" +
	"\tGetPodIPs\x12,.containerd.services.pod.v1.GetPodIPsRequest\x1a-.containerd.services.pod.v1.GetPodIPsResponseB:Z8github.com/containerd/containerd/api/services/pod/v1;podb\x06proto3"

var (
	file_services_pod_v1_pod_proto_rawDescOnce sync.Once
	file_services_pod_v1_pod_proto_rawDescData []byte
)

func file_services_pod_v1_pod_proto_rawDescGZIP() []byte {
	file_services_pod_v1_pod_proto_rawDescOnce.Do(func() {
		file_services_pod_v1_pod_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_pod_v1_pod_proto_rawDesc), len(file_services_pod_v1_pod_proto_rawDesc)))
	})
	return file_services_pod_v1_pod_proto_rawDescData
}

var file_services_pod_v1_pod_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_services_pod_v1_pod_proto_goTypes = []any{
	(*GetPodResourcesRequest)(nil),  // 0: containerd.services.pod.v1.GetPodResourcesRequest
	(*GetPodResourcesResponse)(nil), // 1: containerd.services.pod.v1.GetPodResourcesResponse
	(*GetPodIPsRequest)(nil),        // 2: containerd.services.pod.v1.GetPodIPsRequest
	(*PodInterfaceIPs)(nil),         // 3: containerd.services.pod.v1.PodInterfaceIPs
	(*PodRoute)(nil),                // 4: containerd.services.pod.v1.PodRoute
	(*GetPodIPsResponse)(nil),       // 5: containerd.services.pod.v1.GetPodIPsResponse
	nil,                             // 6: containerd.services.pod.v1.GetPodIPsResponse.InterfaceIpsEntry
}
var file_services_pod_v1_pod_proto_depIdxs = []int32{
	6, // 0: containerd.services.pod.v1.GetPodIPsResponse.interface_ips:type_name -> containerd.services.pod.v1.GetPodIPsResponse.InterfaceIpsEntry
	4, // 1: containerd.services.pod.v1.GetPodIPsResponse.routes:type_name -> containerd.services.pod.v1.PodRoute
	3, // 2: containerd.services.pod.v1.GetPodIPsResponse.InterfaceIpsEntry.value:type_name -> containerd.services.pod.v1.PodInterfaceIPs
	0, // 3: containerd.services.pod.v1.Pod.GetPodResources:input_type -> containerd.services.pod.v1.GetPodResourcesRequest
	2, // 4: containerd.services.pod.v1.Pod.GetPodIPs:input_type -> containerd.services.pod.v1.GetPodIPsRequest
	1, // 5: containerd.services.pod.v1.Pod.GetPodResources:output_type -> containerd.services.pod.v1.GetPodResourcesResponse
	5, // 6: containerd.services.pod.v1.Pod.GetPodIPs:output_type -> containerd.services.pod.v1.GetPodIPsResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_services_pod_v1_pod_proto_init() }
func file_services_pod_v1_pod_proto_init() {
	if File_services_pod_v1_pod_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_pod_v1_pod_proto_rawDesc), len(file_services_pod_v1_pod_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_pod_v1_pod_proto_goTypes,
		DependencyIndexes: file_services_pod_v1_pod_proto_depIdxs,
		MessageInfos:      file_services_pod_v1_pod_proto_msgTypes,
	}.Build()
	File_services_pod_v1_pod_proto = out.File
	file_services_pod_v1_pod_proto_goTypes = nil
	file_services_pod_v1_pod_proto_depIdxs = nil
}
