// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: services/pod/v1/pod.proto

package pod

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PodClient is the client API for Pod service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PodClient interface {
	// GetPodResources returns resources associated with a pod sandbox.
	GetPodResources(ctx context.Context, in *GetPodResourcesRequest, opts ...grpc.CallOption) (*GetPodResourcesResponse, error)
	// GetPodIPs returns the IP addresses assigned to a pod sandbox.
	GetPodIPs(ctx context.Context, in *GetPodIPsRequest, opts ...grpc.CallOption) (*GetPodIPsResponse, error)
}

type podClient struct {
	cc grpc.ClientConnInterface
}

func NewPodClient(cc grpc.ClientConnInterface) PodClient {
	return &podClient{cc}
}

func (c *podClient) GetPodResources(ctx context.Context, in *GetPodResourcesRequest, opts ...grpc.CallOption) (*GetPodResourcesResponse, error) {
	out := new(GetPodResourcesResponse)
	err := c.cc.Invoke(ctx, "/containerd.services.pod.v1.Pod/GetPodResources", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podClient) GetPodIPs(ctx context.Context, in *GetPodIPsRequest, opts ...grpc.CallOption) (*GetPodIPsResponse, error) {
	out := new(GetPodIPsResponse)
	err := c.cc.Invoke(ctx, "/containerd.services.pod.v1.Pod/GetPodIPs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PodServer is the server API for Pod service.
// All implementations must embed UnimplementedPodServer
// for forward compatibility
type PodServer interface {
	// GetPodResources returns resources associated with a pod sandbox.
	GetPodResources(context.Context, *GetPodResourcesRequest) (*GetPodResourcesResponse, error)
	// GetPodIPs returns the IP addresses assigned to a pod sandbox.
	GetPodIPs(context.Context, *GetPodIPsRequest) (*GetPodIPsResponse, error)
	mustEmbedUnimplementedPodServer()
}

// UnimplementedPodServer must be embedded to have forward compatible implementations.
type UnimplementedPodServer struct {
}

func (UnimplementedPodServer) GetPodResources(context.Context, *GetPodResourcesRequest) (*GetPodResourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPodResources not implemented")
}
func (UnimplementedPodServer) GetPodIPs(context.Context, *GetPodIPsRequest) (*GetPodIPsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPodIPs not implemented")
}
func (UnimplementedPodServer) mustEmbedUnimplementedPodServer() {}

// UnsafePodServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PodServer will
// result in compilation errors.
type UnsafePodServer interface {
	mustEmbedUnimplementedPodServer()
}

func RegisterPodServer(s grpc.ServiceRegistrar, srv PodServer) {
	s.RegisterService(&Pod_ServiceDesc, srv)
}

func _Pod_GetPodResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPodResourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodServer).GetPodResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containerd.services.pod.v1.Pod/GetPodResources",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodServer).GetPodResources(ctx, req.(*GetPodResourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pod_GetPodIPs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPodIPsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodServer).GetPodIPs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containerd.services.pod.v1.Pod/GetPodIPs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodServer).GetPodIPs(ctx, req.(*GetPodIPsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Pod_ServiceDesc is the grpc.ServiceDesc for Pod service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Pod_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "containerd.services.pod.v1.Pod",
	HandlerType: (*PodServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPodResources",
			Handler:    _Pod_GetPodResources_Handler,
		},
		{
			MethodName: "GetPodIPs",
			Handler:    _Pod_GetPodIPs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/pod/v1/pod.proto",
}
