// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: services/pod/v1/pod.proto

package pod

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PodClient is the client API for Pod service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PodClient interface {
	// GetPodResources returns resources associated with a pod sandbox.
	GetPodResources(ctx context.Context, in *GetPodResourcesRequest, opts ...grpc.CallOption) (*GetPodResourcesResponse, error)
	// GetPodIPs returns the IP addresses assigned to a pod sandbox.
	GetPodIPs(ctx context.Context, in *GetPodIPsRequest, opts ...grpc.CallOption) (*GetPodIPsResponse, error)
	// GetPodNetwork returns the full network state of a pod sandbox,
	// including all interfaces, IP addresses, routes, and routing rules.
	GetPodNetwork(ctx context.Context, in *GetPodNetworkRequest, opts ...grpc.CallOption) (*GetPodNetworkResponse, error)
	// MoveDevice moves a network device (netdev or RDMA) from the root
	// network namespace into the pod sandbox's network namespace. Any IP
	// addresses, routes, and routing rules associated with the device in
	// the root namespace are preserved and applied in the target namespace.
	MoveDevice(ctx context.Context, in *MoveDeviceRequest, opts ...grpc.CallOption) (*MoveDeviceResponse, error)
	// AssignIPAddress assigns an IP address to an interface within the
	// pod sandbox's network namespace.
	AssignIPAddress(ctx context.Context, in *AssignIPAddressRequest, opts ...grpc.CallOption) (*AssignIPAddressResponse, error)
	// ApplyRoute adds a route in the pod sandbox's network namespace.
	ApplyRoute(ctx context.Context, in *ApplyRouteRequest, opts ...grpc.CallOption) (*ApplyRouteResponse, error)
	// ApplyRule adds an ip rule in the pod sandbox's network namespace.
	ApplyRule(ctx context.Context, in *ApplyRuleRequest, opts ...grpc.CallOption) (*ApplyRuleResponse, error)
	// CreateNetdev creates a new Linux network device inside the pod
	// sandbox's network namespace. Supports veth, vxlan, dummy, ipvlan,
	// and macvlan device types.
	CreateNetdev(ctx context.Context, in *CreateNetdevRequest, opts ...grpc.CallOption) (*CreateNetdevResponse, error)
}

type podClient struct {
	cc grpc.ClientConnInterface
}

func NewPodClient(cc grpc.ClientConnInterface) PodClient {
	return &podClient{cc}
}

func (c *podClient) GetPodResources(ctx context.Context, in *GetPodResourcesRequest, opts ...grpc.CallOption) (*GetPodResourcesResponse, error) {
	out := new(GetPodResourcesResponse)
	err := c.cc.Invoke(ctx, "/containerd.services.pod.v1.Pod/GetPodResources", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podClient) GetPodIPs(ctx context.Context, in *GetPodIPsRequest, opts ...grpc.CallOption) (*GetPodIPsResponse, error) {
	out := new(GetPodIPsResponse)
	err := c.cc.Invoke(ctx, "/containerd.services.pod.v1.Pod/GetPodIPs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podClient) GetPodNetwork(ctx context.Context, in *GetPodNetworkRequest, opts ...grpc.CallOption) (*GetPodNetworkResponse, error) {
	out := new(GetPodNetworkResponse)
	err := c.cc.Invoke(ctx, "/containerd.services.pod.v1.Pod/GetPodNetwork", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podClient) MoveDevice(ctx context.Context, in *MoveDeviceRequest, opts ...grpc.CallOption) (*MoveDeviceResponse, error) {
	out := new(MoveDeviceResponse)
	err := c.cc.Invoke(ctx, "/containerd.services.pod.v1.Pod/MoveDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podClient) AssignIPAddress(ctx context.Context, in *AssignIPAddressRequest, opts ...grpc.CallOption) (*AssignIPAddressResponse, error) {
	out := new(AssignIPAddressResponse)
	err := c.cc.Invoke(ctx, "/containerd.services.pod.v1.Pod/AssignIPAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podClient) ApplyRoute(ctx context.Context, in *ApplyRouteRequest, opts ...grpc.CallOption) (*ApplyRouteResponse, error) {
	out := new(ApplyRouteResponse)
	err := c.cc.Invoke(ctx, "/containerd.services.pod.v1.Pod/ApplyRoute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podClient) ApplyRule(ctx context.Context, in *ApplyRuleRequest, opts ...grpc.CallOption) (*ApplyRuleResponse, error) {
	out := new(ApplyRuleResponse)
	err := c.cc.Invoke(ctx, "/containerd.services.pod.v1.Pod/ApplyRule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podClient) CreateNetdev(ctx context.Context, in *CreateNetdevRequest, opts ...grpc.CallOption) (*CreateNetdevResponse, error) {
	out := new(CreateNetdevResponse)
	err := c.cc.Invoke(ctx, "/containerd.services.pod.v1.Pod/CreateNetdev", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PodServer is the server API for Pod service.
// All implementations must embed UnimplementedPodServer
// for forward compatibility
type PodServer interface {
	// GetPodResources returns resources associated with a pod sandbox.
	GetPodResources(context.Context, *GetPodResourcesRequest) (*GetPodResourcesResponse, error)
	// GetPodIPs returns the IP addresses assigned to a pod sandbox.
	GetPodIPs(context.Context, *GetPodIPsRequest) (*GetPodIPsResponse, error)
	// GetPodNetwork returns the full network state of a pod sandbox,
	// including all interfaces, IP addresses, routes, and routing rules.
	GetPodNetwork(context.Context, *GetPodNetworkRequest) (*GetPodNetworkResponse, error)
	// MoveDevice moves a network device (netdev or RDMA) from the root
	// network namespace into the pod sandbox's network namespace. Any IP
	// addresses, routes, and routing rules associated with the device in
	// the root namespace are preserved and applied in the target namespace.
	MoveDevice(context.Context, *MoveDeviceRequest) (*MoveDeviceResponse, error)
	// AssignIPAddress assigns an IP address to an interface within the
	// pod sandbox's network namespace.
	AssignIPAddress(context.Context, *AssignIPAddressRequest) (*AssignIPAddressResponse, error)
	// ApplyRoute adds a route in the pod sandbox's network namespace.
	ApplyRoute(context.Context, *ApplyRouteRequest) (*ApplyRouteResponse, error)
	// ApplyRule adds an ip rule in the pod sandbox's network namespace.
	ApplyRule(context.Context, *ApplyRuleRequest) (*ApplyRuleResponse, error)
	// CreateNetdev creates a new Linux network device inside the pod
	// sandbox's network namespace. Supports veth, vxlan, dummy, ipvlan,
	// and macvlan device types.
	CreateNetdev(context.Context, *CreateNetdevRequest) (*CreateNetdevResponse, error)
	mustEmbedUnimplementedPodServer()
}

// UnimplementedPodServer must be embedded to have forward compatible implementations.
type UnimplementedPodServer struct {
}

func (UnimplementedPodServer) GetPodResources(context.Context, *GetPodResourcesRequest) (*GetPodResourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPodResources not implemented")
}
func (UnimplementedPodServer) GetPodIPs(context.Context, *GetPodIPsRequest) (*GetPodIPsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPodIPs not implemented")
}
func (UnimplementedPodServer) GetPodNetwork(context.Context, *GetPodNetworkRequest) (*GetPodNetworkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPodNetwork not implemented")
}
func (UnimplementedPodServer) MoveDevice(context.Context, *MoveDeviceRequest) (*MoveDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MoveDevice not implemented")
}
func (UnimplementedPodServer) AssignIPAddress(context.Context, *AssignIPAddressRequest) (*AssignIPAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignIPAddress not implemented")
}
func (UnimplementedPodServer) ApplyRoute(context.Context, *ApplyRouteRequest) (*ApplyRouteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyRoute not implemented")
}
func (UnimplementedPodServer) ApplyRule(context.Context, *ApplyRuleRequest) (*ApplyRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyRule not implemented")
}
func (UnimplementedPodServer) CreateNetdev(context.Context, *CreateNetdevRequest) (*CreateNetdevResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNetdev not implemented")
}
func (UnimplementedPodServer) mustEmbedUnimplementedPodServer() {}

// UnsafePodServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PodServer will
// result in compilation errors.
type UnsafePodServer interface {
	mustEmbedUnimplementedPodServer()
}

func RegisterPodServer(s grpc.ServiceRegistrar, srv PodServer) {
	s.RegisterService(&Pod_ServiceDesc, srv)
}

func _Pod_GetPodResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPodResourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodServer).GetPodResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containerd.services.pod.v1.Pod/GetPodResources",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodServer).GetPodResources(ctx, req.(*GetPodResourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pod_GetPodIPs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPodIPsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodServer).GetPodIPs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containerd.services.pod.v1.Pod/GetPodIPs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodServer).GetPodIPs(ctx, req.(*GetPodIPsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pod_GetPodNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPodNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodServer).GetPodNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containerd.services.pod.v1.Pod/GetPodNetwork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodServer).GetPodNetwork(ctx, req.(*GetPodNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pod_MoveDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodServer).MoveDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containerd.services.pod.v1.Pod/MoveDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodServer).MoveDevice(ctx, req.(*MoveDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pod_AssignIPAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignIPAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodServer).AssignIPAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containerd.services.pod.v1.Pod/AssignIPAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodServer).AssignIPAddress(ctx, req.(*AssignIPAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pod_ApplyRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodServer).ApplyRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containerd.services.pod.v1.Pod/ApplyRoute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodServer).ApplyRoute(ctx, req.(*ApplyRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pod_ApplyRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodServer).ApplyRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containerd.services.pod.v1.Pod/ApplyRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodServer).ApplyRule(ctx, req.(*ApplyRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pod_CreateNetdev_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNetdevRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodServer).CreateNetdev(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containerd.services.pod.v1.Pod/CreateNetdev",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodServer).CreateNetdev(ctx, req.(*CreateNetdevRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Pod_ServiceDesc is the grpc.ServiceDesc for Pod service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Pod_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "containerd.services.pod.v1.Pod",
	HandlerType: (*PodServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPodResources",
			Handler:    _Pod_GetPodResources_Handler,
		},
		{
			MethodName: "GetPodIPs",
			Handler:    _Pod_GetPodIPs_Handler,
		},
		{
			MethodName: "GetPodNetwork",
			Handler:    _Pod_GetPodNetwork_Handler,
		},
		{
			MethodName: "MoveDevice",
			Handler:    _Pod_MoveDevice_Handler,
		},
		{
			MethodName: "AssignIPAddress",
			Handler:    _Pod_AssignIPAddress_Handler,
		},
		{
			MethodName: "ApplyRoute",
			Handler:    _Pod_ApplyRoute_Handler,
		},
		{
			MethodName: "ApplyRule",
			Handler:    _Pod_ApplyRule_Handler,
		},
		{
			MethodName: "CreateNetdev",
			Handler:    _Pod_CreateNetdev_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/pod/v1/pod.proto",
}
