// Code generated by protoc-gen-go-ttrpc. DO NOT EDIT.
// source: services/networking/v1/networking.proto
package networking

import (
	context "context"
	ttrpc "github.com/containerd/ttrpc"
)

type TTRPCPodNetworkLifecycleService interface {
	SetupPodNetwork(context.Context, *SetupPodNetworkRequest) (*SetupPodNetworkResponse, error)
	TeardownPodNetwork(context.Context, *TeardownPodNetworkRequest) (*TeardownPodNetworkResponse, error)
	CheckHealth(context.Context, *CheckHealthRequest) (*CheckHealthResponse, error)
}

func RegisterTTRPCPodNetworkLifecycleService(srv *ttrpc.Server, svc TTRPCPodNetworkLifecycleService) {
	srv.RegisterService("containerd.services.networking.v1.PodNetworkLifecycle", &ttrpc.ServiceDesc{
		Methods: map[string]ttrpc.Method{
			"SetupPodNetwork": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req SetupPodNetworkRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.SetupPodNetwork(ctx, &req)
			},
			"TeardownPodNetwork": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req TeardownPodNetworkRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.TeardownPodNetwork(ctx, &req)
			},
			"CheckHealth": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req CheckHealthRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.CheckHealth(ctx, &req)
			},
		},
	})
}

type ttrpcpodnetworklifecycleClient struct {
	client *ttrpc.Client
}

func NewTTRPCPodNetworkLifecycleClient(client *ttrpc.Client) TTRPCPodNetworkLifecycleService {
	return &ttrpcpodnetworklifecycleClient{
		client: client,
	}
}

func (c *ttrpcpodnetworklifecycleClient) SetupPodNetwork(ctx context.Context, req *SetupPodNetworkRequest) (*SetupPodNetworkResponse, error) {
	var resp SetupPodNetworkResponse
	if err := c.client.Call(ctx, "containerd.services.networking.v1.PodNetworkLifecycle", "SetupPodNetwork", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *ttrpcpodnetworklifecycleClient) TeardownPodNetwork(ctx context.Context, req *TeardownPodNetworkRequest) (*TeardownPodNetworkResponse, error) {
	var resp TeardownPodNetworkResponse
	if err := c.client.Call(ctx, "containerd.services.networking.v1.PodNetworkLifecycle", "TeardownPodNetwork", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *ttrpcpodnetworklifecycleClient) CheckHealth(ctx context.Context, req *CheckHealthRequest) (*CheckHealthResponse, error) {
	var resp CheckHealthResponse
	if err := c.client.Call(ctx, "containerd.services.networking.v1.PodNetworkLifecycle", "CheckHealth", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

type TTRPCPodNetworkManagementService interface {
	GetPodResources(context.Context, *GetPodResourcesRequest) (*GetPodResourcesResponse, error)
	GetPodIPs(context.Context, *GetPodIPsRequest) (*GetPodIPsResponse, error)
	GetPodNetwork(context.Context, *GetPodNetworkRequest) (*GetPodNetworkResponse, error)
	MoveDevice(context.Context, *MoveDeviceRequest) (*MoveDeviceResponse, error)
	AssignIPAddress(context.Context, *AssignIPAddressRequest) (*AssignIPAddressResponse, error)
	ApplyRoute(context.Context, *ApplyRouteRequest) (*ApplyRouteResponse, error)
	ApplyRule(context.Context, *ApplyRuleRequest) (*ApplyRuleResponse, error)
	CreateNetdev(context.Context, *CreateNetdevRequest) (*CreateNetdevResponse, error)
	AttachInterface(context.Context, *AttachInterfaceRequest) (*AttachInterfaceResponse, error)
}

func RegisterTTRPCPodNetworkManagementService(srv *ttrpc.Server, svc TTRPCPodNetworkManagementService) {
	srv.RegisterService("containerd.services.networking.v1.PodNetworkManagement", &ttrpc.ServiceDesc{
		Methods: map[string]ttrpc.Method{
			"GetPodResources": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req GetPodResourcesRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.GetPodResources(ctx, &req)
			},
			"GetPodIPs": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req GetPodIPsRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.GetPodIPs(ctx, &req)
			},
			"GetPodNetwork": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req GetPodNetworkRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.GetPodNetwork(ctx, &req)
			},
			"MoveDevice": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req MoveDeviceRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.MoveDevice(ctx, &req)
			},
			"AssignIPAddress": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req AssignIPAddressRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.AssignIPAddress(ctx, &req)
			},
			"ApplyRoute": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req ApplyRouteRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.ApplyRoute(ctx, &req)
			},
			"ApplyRule": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req ApplyRuleRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.ApplyRule(ctx, &req)
			},
			"CreateNetdev": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req CreateNetdevRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.CreateNetdev(ctx, &req)
			},
			"AttachInterface": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req AttachInterfaceRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.AttachInterface(ctx, &req)
			},
		},
	})
}

type ttrpcpodnetworkmanagementClient struct {
	client *ttrpc.Client
}

func NewTTRPCPodNetworkManagementClient(client *ttrpc.Client) TTRPCPodNetworkManagementService {
	return &ttrpcpodnetworkmanagementClient{
		client: client,
	}
}

func (c *ttrpcpodnetworkmanagementClient) GetPodResources(ctx context.Context, req *GetPodResourcesRequest) (*GetPodResourcesResponse, error) {
	var resp GetPodResourcesResponse
	if err := c.client.Call(ctx, "containerd.services.networking.v1.PodNetworkManagement", "GetPodResources", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *ttrpcpodnetworkmanagementClient) GetPodIPs(ctx context.Context, req *GetPodIPsRequest) (*GetPodIPsResponse, error) {
	var resp GetPodIPsResponse
	if err := c.client.Call(ctx, "containerd.services.networking.v1.PodNetworkManagement", "GetPodIPs", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *ttrpcpodnetworkmanagementClient) GetPodNetwork(ctx context.Context, req *GetPodNetworkRequest) (*GetPodNetworkResponse, error) {
	var resp GetPodNetworkResponse
	if err := c.client.Call(ctx, "containerd.services.networking.v1.PodNetworkManagement", "GetPodNetwork", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *ttrpcpodnetworkmanagementClient) MoveDevice(ctx context.Context, req *MoveDeviceRequest) (*MoveDeviceResponse, error) {
	var resp MoveDeviceResponse
	if err := c.client.Call(ctx, "containerd.services.networking.v1.PodNetworkManagement", "MoveDevice", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *ttrpcpodnetworkmanagementClient) AssignIPAddress(ctx context.Context, req *AssignIPAddressRequest) (*AssignIPAddressResponse, error) {
	var resp AssignIPAddressResponse
	if err := c.client.Call(ctx, "containerd.services.networking.v1.PodNetworkManagement", "AssignIPAddress", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *ttrpcpodnetworkmanagementClient) ApplyRoute(ctx context.Context, req *ApplyRouteRequest) (*ApplyRouteResponse, error) {
	var resp ApplyRouteResponse
	if err := c.client.Call(ctx, "containerd.services.networking.v1.PodNetworkManagement", "ApplyRoute", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *ttrpcpodnetworkmanagementClient) ApplyRule(ctx context.Context, req *ApplyRuleRequest) (*ApplyRuleResponse, error) {
	var resp ApplyRuleResponse
	if err := c.client.Call(ctx, "containerd.services.networking.v1.PodNetworkManagement", "ApplyRule", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *ttrpcpodnetworkmanagementClient) CreateNetdev(ctx context.Context, req *CreateNetdevRequest) (*CreateNetdevResponse, error) {
	var resp CreateNetdevResponse
	if err := c.client.Call(ctx, "containerd.services.networking.v1.PodNetworkManagement", "CreateNetdev", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *ttrpcpodnetworkmanagementClient) AttachInterface(ctx context.Context, req *AttachInterfaceRequest) (*AttachInterfaceResponse, error) {
	var resp AttachInterfaceResponse
	if err := c.client.Call(ctx, "containerd.services.networking.v1.PodNetworkManagement", "AttachInterface", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
